client:
  pk: id
  fields:
    id: INT NOT NULL AUTO_INCREMENT
    name: VARCHAR(32)
    phone: VARCHAR(100)
    mobile: VARCHAR(100)
    wechat: VARCHAR(30)
    qq: VARCHAR(20)
    email: VARCHAR(100)
    address: VARCHAR(512)
    comment: TEXT
    source_date: INT
    stared: TINYINT(1) DEFAULT 0
    imported_to_google: TINYINT(1) DEFAULT 0

  indexes:
    - `client_phone` (`phone` ASC)
    - `client_mobile` (`mobile` ASC)
    - `client_email` (`email` ASC)
    - `client_stared` (`stared` ASC)
    
  form:
    fields:
      name:
        widget: text
        widget_conf:
          required: 0
      phone:
        widget: text
        widget_conf:
          required: 0
      mobile:
        widget: text
        widget_conf:
          required: 0
      wechat:
        widget: text
        widget_conf:
          required: 0
      qq:
        widget: text
        widget_conf:
          required: 0
      email:
        widget: text
        widget_conf:
          required: 0
      address:
        widget: textarea
        widget_conf:
          required: 0
          wysiwyg: 0
      comment:
        widget: textarea
        widget_conf:
          required: 0
          wysiwyg: 1
      source_date:
        widget: text
        widget_conf:
          required: 0
      stared:
        widget: checkbox_single
          
        
    names:
      en: Client
      zh: 客户

    
#project:
#  pk: id
#  fields:
#    id: INT NOT NULL AUTO_INCREMENT
#    title: VARCHAR(512) NOT NULL
#    password: VARCHAR(20)
#    email: VARCHAR(30)
#    description_en: TEXT
#    description_zh: TEXT
#    active: TINYINT(1) DEFAULT 1
#    hot: TINYINT(1) DEFAULT 1
#    price: DECIMAL(6) DEFAULT 0
#    images: VARCHAR(800)
#    thumbnail: VARCHAR(100)
#  form:
#    fields:
#      title:
#        widget: text
#        widget_conf:
#          required: 1
#          size: 150
#      password:
#        widget: password
#        widget_conf:
#          required: 1
#          size: 15
#      email:
#        widget: email
#        widget_conf:
#          required: 1
#          size: 30
#      description_en:
#        widget: textarea
#        widget_conf:
#          required: 0
#          wysiwyg: 1
#      description_zh:
#        widget: textarea
#        widget_conf:
#          required: 1
#          wysiwyg: 0
#      active:
#        widget: checkbox_single
#        widget_conf: 
#      owners:
#        widget: checkbox_multiple
#        widget_conf:
#          required: 1
#          options:
#            jack: Jack
#            sue: Sue
#      price:
#        widget: select
#        widget_conf:
#          required: 0
#          options:
#            0: -- Select --
#            34: $34
#            45: $45
#      images:
#        widget: image
#        widget_conf:
#          required: 0
#          multiple: 1
#          upload_dir: files/fields/images
#          transform:
#            dimension: 500x320
#            refill: "0,0,0"
#            watermark: modules/site/assets/images/favicon.png
#      thumbnail:
#        widget: image
#        widget_conf:
#          required: 1
#          multiple: 0
#          upload_dir: files/fields/thumbnail
#          transform: 0
#
#            
#            
#          
#        
#    names:
#      en: Project
#      zh: 项目
#
#    
#    